### PR TITLE
Implements support for the common responses endpoint

### PR DESCRIPTION
**Pull request by esjee**
This endpoint returns a list of common responses, complete with id, title, and message.

### CODE REVIEW

**Comment by oreoshake** [comment]
:heart: thanks @esjee! It may take another week for me to get to this but this and the payment API are on the top of my backlog.

**Comment by oreoshake** [comment]
Is there going to be an endpoint that specifically requests an individual common response referenced by ID? For now, it looks like we'll have to pull them all down and search locally a la 

```ruby
HackerOne::Client::Program.find("insert-program-name").common_responses.find {|r| r[:id] == "12345"}
```

Just curious if that's available or coming soon, I'm happy to ship this and iterate. I doubt that anyone has enough common responses in a single program to cause any problems, but so far we only really need to pull down 2 responses.

**Comment by oreoshake** [comment]
Just kidding, I felt like procrastinating on my more pressing issues for some quick wins here. Released in 0.7.0

**Comment by esjee** [comment]
:smile: 

Please let me know if you (or anybody else) runs into that issue! For now, I hope this is good enough. There's plenty of other features left to implement as well :sweat_smile:

**Pull request merged**
